const classes = {
  container: ["p-4", "pb-16"],
  ol: ["flex", "justify-center", "gap-1", "text-xs", "font-medium"],
  prevNext: [
    "inline-flex",
    "h-8",
    "w-8",
    "items-center",
    "justify-center",
    "rounded",
    "border",
    "border-gray-100",
    "bg-white",
    "text-gray-900",
    "rtl:rotate-180",
  ],
  page: [
    "block",
    "h-8",
    "w-8",
    "rounded",
    "border",
    "border-gray-100",
    "bg-white",
    "text-center",
    "leading-8",
    "text-gray-900",
  ],
  active: [
    "block",
    "h-8",
    "w-8",
    "rounded",
    "border-blue-600",
    "bg-blue-600",
    "text-center",
    "leading-8",
    "text-white",
  ],
};

export default classes;
