const classes = {
  wrapper: ["flex", "lg:space-x-16", "max-lg:flex-col", "max-lg:space-y-8"],
  form: ["rounded-lg", "border", "w-full"],
  form2: ["rounded-lg", "border", "h-full", "w-full"],
  formGroup: ["flex", "flex-col", "gap-4", "p-4", "md:p-8"],
  label: ["mb-2", "inline-block", "text-sm", "text-gray-800", "sm:text-base"],
  input: [
    "w-full",
    "rounded",
    "border",
    "bg-gray-50",
    "px-3",
    "py-2",
    "text-gray-800",
    "outline-none",
    "ring-indigo-300",
    "transition",
    "duration-100",
    "focus:ring",
  ],
  button: [
    "block",
    "rounded-lg",
    "bg-gray-800",
    "px-8",
    "py-3",
    "mt-4",
    "text-center",
    "text-sm",
    "font-semibold",
    "text-white",
    "outline-none",
    "ring-gray-300",
    "transition",
    "duration-100",
    "hover:bg-gray-700",
    "focus-visible:ring",
    "active:bg-gray-600",
    "md:text-base",
  ],
};

export default classes;
