const classes = {
  label: ["mb-2", "inline-block", "text-sm", "text-gray-800", "sm:text-base"],
  inputGroup: ["my-8", "flex", "flex-col"],
  input: [
    "rounded",
    "border",
    "bg-gray-50",
    "px-3",
    "py-2",
    "text-gray-800",
    "outline-none",
    "ring-emerald-300",
    "transition",
    "duration-100",
    "focus:ring",
    "-mb-2",
  ],
  button: [
    "inline-flex",
    "justify-center",
    "rounded-md",
    "border",
    "border-transparent",
    "shadow-sm",
    "px-4",
    "py-2",
    "bg-emerald-600",
    "text-base",
    "font-medium",
    "text-white",
    "hover:bg-emerald-700",
    "focus:outline-none",
    "focus:ring-2",
    "focus:ring-offset-2",
    "focus:ring-emerald-500",
    "sm:w-auto",
    "sm:text-sm",
  ],
};

export default classes;
