const classes = {
  container: ["bg-white", "py-6", "sm:py-8", "lg:py-12"],
  wrapper: ["mx-auto", "max-w-screen-2xl", "px-4", "md:px-8"],
  title: [
    "mb-4",
    "text-center",
    "text-2xl",
    "font-bold",
    "text-gray-800",
    "md:mb-8",
    "lg:text-3xl",
  ],
  grid: [
    "container",
    "mx-auto",
    "grid",
    "sm:grid-cols-1",
    "md:grid-cols-2",
    "lg:grid-cols-3",
    "xl:grid-cols-4",
    "pt-6",
    "gap-8",
  ],
  image: [
    "object-center",
    "object-cover",
    "rounded-full",
    "w-56",
    "h-56",
    "mt-8",
  ],
  section: ["pt-16", "pb-24", "bg-slate-50"],
  cardWrapper: ["w-full", "lg:w-4/12", "px-4", "mx-auto"],
  cardContainer: [
    "relative",
    "flex",
    "flex-col",
    "min-w-0",
    "break-words",
    "bg-white",
    "w-full",
    "mb-6",
    "shadow-xl",
    "rounded-lg",
    "mt-16",
  ],
  profileWrapper: ["flex", "flex-wrap", "justify-center"],
  profileContainer: ["w-full", "px-4", "flex", "justify-center"],
  textContainer: ["text-center", "mt-8"],
  name: [
    "text-xl",
    "font-semibold",
    "leading-normal",
    "mb-2",
    "text-blueGray-700",
    "mb-2",
  ],
  location: [
    "text-sm",
    "leading-normal",
    "mt-0",
    "mb-2",
    "text-blueGray-400",
    "font-bold",
    "uppercase",
  ],
  job: ["mb-2", "text-blueGray-600", "mt-0"],
  descriptionArea: [
    "mt-10",
    "py-10",
    "border-t",
    "border-blueGray-200",
    "text-center",
  ],
  descriptionWrapper: ["flex", "flex-wrap", "justify-center"],
  descriptionContainer: ["w-full", "lg:w-9/12", "px-4"],
  description: [
    "mb-10",
    "text-lg",
    "leading-relaxed",
    "text-blueGray-700",
    "text-start",
  ],
  scheduleButton: [
    "rounded-md",
    "flex",
    "space-x-2",
    "w-56",
    "h-10",
    "font-normal",
    "text-sm",
    "leading-3",
    "text-emerald-700",
    "bg-white",
    "border",
    "border-emerald-700",
    "focus:outline-none",
    "focus:bg-emerald-700",
    "hover:bg-emerald-700",
    "focus:text-white",
    "hover:text-white",
    "duration-150",
    "justify-center",
    "items-center",
    "mx-auto",
  ],
};

export default classes;
