const classes = {
  container: [
    "p-16",
    "m-12",
    "bg-slate-100",
    "rounded",
    "border",
    "flex",
    "flex-col",
    "space-y-6",
    "sm: m-0",
    "sm: mt-8",
  ],
  inputGroup: ["flex", "flex-col", "space-y-2"],
  label: ["leading-7", "text-sm", "text-gray-600"],
  input: [
    "w-full",
    "bg-white",
    "rounded",
    "border",
    "border-gray-300",
    "focus:border-emerald-500",
    "focus:ring-2",
    "focus:ring-emerald-200",
    "text-base",
    "outline-none",
    "text-gray-700",
    "py-1",
    "px-3",
    "leading-8",
    "transition-colors",
    "duration-200",
    "ease-in-out",
  ],
  inputSelect: [
    "w-full",
    "bg-white",
    "rounded",
    "border",
    "border-gray-300",
    "focus:border-emerald-500",
    "focus:ring-2",
    "focus:ring-emerald-200",
    "text-base",
    "outline-none",
    "text-gray-700",
    "py-3",
    "px-3",
    "leading-8",
    "transition-colors",
    "duration-200",
    "ease-in-out",
  ],
  button: [
    "w-full",
    "bg-emerald-600",
    "rounded",
    "shadow",
    "p-2",
    "mt-12",
    "text-slate-200",
    "hover:bg-emerald-700",
  ],
};

export default classes;
