const classes = {
  area: ["mx-auto", "rounded-lg", "border", "p-8"],
  inputGroup: [
    "mx-auto",
    "grid",
    "sm:grid-cols-1",
    "md:grid-cols-2",
    "lg:grid-cols-3",
    "xl:grid-cols-5",
    "gap-4",
  ],
  label: ["mb-2", "inline-block", "text-sm", "text-gray-800", "sm:text-base"],
  input: [
    "w-full",
    "rounded",
    "border",
    "bg-gray-50",
    "px-3",
    "py-2",
    "text-gray-800",
    "outline-none",
    "ring-indigo-300",
    "transition",
    "duration-100",
    "focus:ring",
  ],
  button: [
    "mt-8",
    "block",
    "rounded-lg",
    "bg-emerald-600",
    "px-8",
    "py-2",
    "text-center",
    "text-sm",
    "font-semibold",
    "text-white",
    "outline-none",
    "ring-gray-300",
    "transition",
    "duration-100",
    "hover:bg-emerald-700",
    "focus-visible:ring",
    "active:bg-emerald-700",
    "md:text-base",
  ],
};

export default classes;
