const classes = {
  container: ["bg-white", "py-6", "sm:py-8", "lg:py-12"],
  wrapper: ["mx-auto", "max-w-screen-2xl", "px-4", "md:px-8"],
  title: [
    "mb-4",
    "text-center",
    "text-2xl",
    "font-bold",
    "text-gray-800",
    "md:mb-8",
    "lg:text-3xl",
  ],
  section: ["pt-16", "pb-24", "bg-slate-50"],
  cardWrapper: ["w-full", "lg:w-6/12", "px-4", "mx-auto"],
  body: [
    "min-w-0",
    "bg-white",
    "w-full",
    "mb-6",
    "shadow-xl",
    "rounded-lg",
    "mt-16",
  ],
  cardContainer: [
    "relative",
    "flex",
    "flex-col",
    "align-center",
    "sm:flex-row",
    "sm:align-init",
    "break-words",
  ],
  imageContainer: ["p-8", "max-sm:mx-auto"],
  image: ["object-center", "object-cover", "rounded-full", "w-40", "h-40"],
  infoContainer: [
    "pt-16",
    "w-full",
    "max-sm:flex",
    "max-sm:flex-col",
    "max-sm:items-center",
    "max-sm:pt-4",
  ],
  name: ["font-bold", "hover:text-gray-600"],
  service: [
    "whitespace-nowrap",
    "rounded",
    "bg-emerald-100",
    "px-2.5",
    "py-0.5",
    "text-sm",
    "text-emerald-700",
    "ml-4",
  ],
  description: ["text-sm", "mt-2", "mr-8", "max-sm:pl-8"],
  button: [
    "rounded-md",
    "flex",
    "space-x-2",
    "w-56",
    "h-10",
    "font-normal",
    "text-sm",
    "leading-3",
    "text-emerald-700",
    "bg-white",
    "border",
    "border-emerald-700",
    "focus:outline-none",
    "focus:bg-emerald-700",
    "hover:bg-emerald-700",
    "focus:text-white",
    "hover:text-white",
    "duration-150",
    "justify-center",
    "items-center",
    "mt-4",
    "max-sm:mt-8",
  ],
  divisor: ["mx-8", "mt-8"],
  grid: [
    "container",
    "mx-auto",
    "grid",
    "sm:grid-cols-1",
    "md:grid-cols-2",
    "lg:grid-cols-3",
    "py-8",
    "gap-8",
    "px-8",
    "max-sm:pl-8",
  ],
};

export default classes;
