const classes = {
  section: ["bg-white", "sticky", "top-0", "z-50"],
  nav: ["2xl:container", "2xl:mx-auto", "sm:py-6", "sm:px-7", "py-5", "px-4"],
  container: ["flex", "justify-between"],
  brandContainer: ["flex", "space-x-3", "items-center"],
  brand: ["font-normal", "text-2xl", "leading-6", "text-gray-800"],
  desktopButtonGroup: ["hidden", "sm:flex", "flex-row", "space-x-4"],
  desktopSignUpButton: [
    "rounded-md",
    "flex",
    "space-x-2",
    "w-24",
    "h-10",
    "font-normal",
    "text-sm",
    "leading-3",
    "text-indigo-700",
    "bg-white",
    "border",
    "border-indigo-700",
    "focus:outline-none",
    "focus:bg-indigo-700",
    "hover:bg-indigo-700",
    "focus:text-white",
    "hover:text-white",
    "duration-150",
    "justify-center",
    "items-center",
  ],
  desktopSignInButton: [
    "rounded-md",
    "flex",
    "space-x-2",
    "w-24",
    "h-10",
    "font-normal",
    "text-sm",
    "leading-3",
    "text-white",
    "bg-indigo-700",
    "focus:outline-none",
    "focus:ring-2",
    "focus:ring-offset-2",
    "focus:ring-indigo-700",
    "focus:bg-indigo-600",
    "hover:bg-indigo-600",
    "duration-150",
    "justify-center",
    "items-center",
  ],
  desktopToggleMenu: [
    "focus:outline-none",
    "focus:ring-2",
    "focus:ring-offset-2",
    "focus:ring-gray-800",
    "",
    "justify-center",
    "items-center",
    "sm:hidden",
    "cursor-pointer",
  ],
  mobileSignUpButton: [
    "rounded-md",
    "flex",
    "space-x-2",
    "w-full",
    "h-10",
    "font-normal",
    "text-sm",
    "leading-3",
    "text-indigo-700",
    "bg-indigo-600",
    "bg-opacity-0",
    "hover:opacity-100",
    "duration-100",
    "border",
    "border-indigo-700",
    "focus:outline-none",
    "focus:bg-gray-200",
    "hover:bg-gray-200",
    "duration-150",
    "justify-center",
    "items-center",
  ],
  mobileSignInButton: [
    "rounded-md",
    "flex",
    "space-x-2",
    "w-full",
    "h-10",
    "font-normal",
    "text-sm",
    "leading-3",
    "text-white",
    "bg-indigo-700",
    "focus:outline-none",
    "focus:ring-2",
    "focus:ring-offset-2",
    "focus:ring-indigo-700",
    "focus:bg-indigo-600",
    "hover:bg-indigo-600",
    "duration-150",
    "justify-center",
    "items-center",
  ],
  mobileButtonGroup: ["flex", "flex-col", "gap-4", "mt-4", "w-80", "mx-auto"],
};

export default classes;
