const classes = {
  aside: [
    "flex",
    "fixed",
    "h-screen",
    "w-64",
    "flex-col",
    "justify-between",
    "border-e",
    "bg-white",
    "max-sm:hidden",
  ],
  asideMobile: [
    "flex",
    "fixed",
    "h-screen",
    "flex-col",
    "justify-between",
    "bg-white",
    "w-screen",
  ],
  brand: [
    "font-bold",
    "text-1xl",
    "leading-6",
    "text-gray-800",
    "w-full",
    "text-center",
  ],
  toggleMenu: [
    "focus:outline-none",
    "focus:ring-2",
    "focus:ring-offset-2",
    "focus:ring-gray-800",
    "justify-center",
    "items-center",
    "sm:hidden",
    "cursor-pointer",
    "ml-auto",
    "-mt-2",
    "absolute",
  ],
  mobileButtonGroup: ["max-sm:block", "sm:hidden", "absolute", "mt-8", "ml-8"],
  nav: ["mt-6", "flex", "flex-col", "space-y-1"],
  menuLink: [
    "flex",
    "items-center",
    "gap-2",
    "rounded-lg",
    "px-4",
    "py-2",
    "text-gray-500",
    "hover:bg-gray-100",
    "hover:text-gray-700",
  ],
  menuLinkActive: [
    "flex",
    "items-center",
    "gap-2",
    "rounded-lg",
    "bg-gray-100",
    "px-4",
    "py-2",
    "text-gray-700",
  ],
  menuLinkText: ["text-sm", "font-medium"],
  menuSelect: ["group", "[&_summary::-webkit-details-marker]:hidden"],
  menuOption: [
    "flex",
    "cursor-pointer",
    "items-center",
    "justify-between",
    "rounded-lg",
    "px-4",
    "py-2",
    "text-gray-500",
    "hover:bg-gray-100",
    "hover:text-gray-700",
  ],
  menuSelectIcon: [
    "shrink-0",
    "transition",
    "duration-300",
    "group-open:-rotate-180",
  ],
  footer: ["sticky", "inset-x-0", "bottom-0", "border-t", "border-gray-100"],
  profileLink: [
    "flex",
    "items-center",
    "gap-2",
    "bg-white",
    "p-4",
    "hover:bg-gray-50",
  ],
  profileImage: ["h-10", "w-10", "rounded-full", "object-cover"],
  logoutButton: [
    "flex",
    "w-full",
    "items-center",
    "gap-2",
    "rounded-lg",
    "px-4",
    "py-2",
    "text-gray-500",
    "hover:bg-gray-100",
    "hover:text-gray-700",
  ],
};

export default classes;
