const classes = {
  main: ["bg-slate-100"],
  container: ["bg-white", "py-6", "sm:py-8", "lg:py-12"],
  wrapper: ["mx-auto", "max-w-screen-2xl", "px-4", "md:px-8"],
  title: [
    "mb-4",
    "text-center",
    "text-2xl",
    "font-bold",
    "text-gray-800",
    "md:mb-8",
    "lg:text-3xl",
  ],
  form: ["mx-auto", "max-w-lg", "rounded-lg", "border"],
  formGroup: ["flex", "flex-col", "gap-4", "p-4", "md:p-8"],
  label: ["mb-2", "inline-block", "text-sm", "text-gray-800", "sm:text-base"],
  input: [
    "w-full",
    "rounded",
    "border",
    "bg-gray-50",
    "px-3",
    "py-2",
    "text-gray-800",
    "outline-none",
    "ring-indigo-300",
    "transition",
    "duration-100",
    "focus:ring",
  ],
  button: [
    "block",
    "rounded-lg",
    "bg-gray-800",
    "px-8",
    "py-3",
    "text-center",
    "text-sm",
    "font-semibold",
    "text-white",
    "outline-none",
    "ring-gray-300",
    "transition",
    "duration-100",
    "hover:bg-gray-700",
    "focus-visible:ring",
    "active:bg-gray-600",
    "md:text-base",
  ],
  loginSocialGroup: ["relative", "flex", "items-center", "justify-center"],
  loginSocialLine: ["absolute", "inset-x-0", "h-px", "bg-gray-300"],
  loginSocialText: ["relative", "bg-white", "px-4", "text-sm", "text-gray-400"],
  googleButton: [
    "flex",
    "items-center",
    "justify-center",
    "gap-2",
    "rounded-lg",
    "border",
    "border-gray-300",
    "bg-white",
    "px-8",
    "py-3",
    "text-center",
    "text-sm",
    "font-semibold",
    "text-gray-800",
    "outline-none",
    "ring-gray-300",
    "transition",
    "duration-100",
    "hover:bg-gray-100",
    "focus-visible:ring",
    "active:bg-gray-200",
    "md:text-base",
  ],
  signupButton: [
    "text-indigo-500",
    "transition",
    "duration-100",
    "hover:text-indigo-600",
    "active:text-indigo-700",
  ],
  haventAccountGroup: [
    "flex",
    "items-center",
    "justify-center",
    "bg-gray-100",
    "p-4",
  ],
  haventAccountText: ["text-center", "text-sm", "text-gray-500"],
};

export default classes;
