const classes = {
  main: ["bg-slate-100"],
  section: ["bg-white", "pb-6", "sm:pb-8", "lg:pb-12"],
  wrapper: ["mx-auto", "max-w-screen-2xl", "px-4", "md:px-8"],
  container: [
    "mb-8",
    "flex",
    "flex-col",
    "justify-between",
    "gap-6",
    "sm:gap-10",
    "md:mb-16",
    "md:gap-16",
    "lg:flex-row",
  ],
  textContainer: [
    "flex",
    "flex-col",
    "justify-center",
    "sm:text-center",
    "lg:py-12",
    "lg:text-left",
    "xl:w-5/12",
  ],
  title: [
    "text-black-800",
    "mb-8",
    "text-4xl",
    "font-bold",
    "sm:text-5xl",
    "md:mb-12",
    "md:text-6xl",
  ],
  subtitle: [
    "mb-4",
    "font-semibold",
    "text-indigo-500",
    "md:mb-6",
    "md:text-lg",
    "xl:text-xl",
  ],
  title2: [
    "title-font",
    "font-bold",
    "text-2xl",
    "text-gray-900",
    "text-center",
    "pb-16",
  ],
  statsContainer: [
    "flex",
    "flex-col",
    "items-center",
    "justify-between",
    "gap-10",
    "border-t",
    "pt-8",
    "lg:flex-row",
    "lg:gap-8",
  ],
  statsWrapper: [
    "-mx-6",
    "grid",
    "grid-cols-2",
    "gap-4",
    "md:-mx-8",
    "md:flex",
    "md:divide-x",
  ],
  stats: ["px-6", "md:px-8"],
  statsNumber: [
    "block",
    "text-center",
    "text-lg",
    "font-bold",
    "text-indigo-500",
    "md:text-left",
    "md:text-xl",
  ],
  statsLabel: [
    "block",
    "text-center",
    "text-sm",
    "font-semibold",
    "text-gray-800",
    "md:text-left",
    "md:text-base",
  ],
  grid: [
    "container",
    "mx-auto",
    "grid",
    "sm:grid-cols-1",
    "md:grid-cols-2",
    "lg:grid-cols-3",
    "xl:grid-cols-4",
    "pt-6",
    "gap-8",
  ],
};

export default classes;
